CREATE SEQUENCE IF NOT EXISTS INTERNAL_TRANSACTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS CUSTOMER_ORDER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ORDER_DETAIL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS CUSTOMER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ORDER_PAYMENT_SEQ START WITH 1 INCREMENT BY 1;
